# Generated by Django 4.2.3 on 2023-07-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
